// <auto-generated />
namespace LK.BL.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class v12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v12));
        
        string IMigrationMetadata.Id
        {
            get { return "202005121922129_v1.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
